#!/usr/bin/env python3
from __future__ import annotations

import argparse
import base64
import math
from pathlib import Path
from xml.sax.saxutils import escape

import cv2

A4_WIDTH_MM = 210.0
A4_HEIGHT_MM = 297.0


def _png_data_uri(image) -> str:
    ok, encoded = cv2.imencode(".png", image)
    if not ok:
        raise RuntimeError("failed to encode tile PNG")
    payload = base64.b64encode(encoded.tobytes()).decode("ascii")
    return f"data:image/png;base64,{payload}"


def _crop_marks(x: float, y: float, w: float, h: float, length: float = 5.0) -> list[str]:
    style = 'stroke="#d00" stroke-width="0.2" fill="none"'
    x2 = x + w
    y2 = y + h
    return [
        f'<path d="M {x:.3f} {y:.3f} h {-length:.3f} M {x:.3f} {y:.3f} v {-length:.3f}" {style}/>',
        f'<path d="M {x2:.3f} {y:.3f} h {length:.3f} M {x2:.3f} {y:.3f} v {-length:.3f}" {style}/>',
        f'<path d="M {x:.3f} {y2:.3f} h {-length:.3f} M {x:.3f} {y2:.3f} v {length:.3f}" {style}/>',
        f'<path d="M {x2:.3f} {y2:.3f} h {length:.3f} M {x2:.3f} {y2:.3f} v {length:.3f}" {style}/>',
    ]


def _render_svg(
    output: Path,
    crop,
    page_col: int,
    page_row: int,
    page_cols: int,
    page_rows: int,
    crop_x_mm: float,
    crop_y_mm: float,
    crop_w_mm: float,
    crop_h_mm: float,
    offset_x_mm: float,
    offset_y_mm: float,
) -> None:
    href = escape(_png_data_uri(crop))
    label = f"tile r{page_row + 1}c{page_col + 1} / {page_rows}x{page_cols}"
    parts = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        (
            f'<svg xmlns="http://www.w3.org/2000/svg" '
            f'width="{A4_WIDTH_MM:.3f}mm" height="{A4_HEIGHT_MM:.3f}mm" '
            f'viewBox="0 0 {A4_WIDTH_MM:.3f} {A4_HEIGHT_MM:.3f}">'
        ),
        '<rect x="0" y="0" width="100%" height="100%" fill="white"/>',
        (
            f'<image x="{offset_x_mm:.6f}" y="{offset_y_mm:.6f}" '
            f'width="{crop_w_mm:.6f}" height="{crop_h_mm:.6f}" '
            f'href="{href}" image-rendering="pixelated"/>'
        ),
        (
            f'<rect x="{offset_x_mm:.6f}" y="{offset_y_mm:.6f}" '
            f'width="{crop_w_mm:.6f}" height="{crop_h_mm:.6f}" '
            f'fill="none" stroke="#d00" stroke-width="0.18" stroke-dasharray="2 1"/>'
        ),
        *_crop_marks(offset_x_mm, offset_y_mm, crop_w_mm, crop_h_mm),
        (
            f'<text x="8" y="{A4_HEIGHT_MM - 6:.3f}" font-family="monospace" '
            f'font-size="3.2" fill="#555">{label}; origin '
            f'{crop_x_mm:.1f},{crop_y_mm:.1f} mm</text>'
        ),
        "</svg>",
    ]
    output.write_text("\n".join(parts) + "\n", encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description="Split a full AprilGrid PNG into printable A4 SVG tiles.")
    parser.add_argument("--input-png", required=True, help="Full artwork PNG generated by generate_kalibr_aprilgrid_artwork.py.")
    parser.add_argument("--board-width-mm", type=float, required=True, help="Physical width of the full artwork, including margin.")
    parser.add_argument("--board-height-mm", type=float, required=True, help="Physical height of the full artwork, including margin.")
    parser.add_argument("--output-dir", required=True)
    parser.add_argument("--printer-margin-mm", type=float, default=8.0, help="Safe unprinted page margin.")
    parser.add_argument("--overlap-mm", type=float, default=12.0, help="Overlap between adjacent pages.")
    args = parser.parse_args()

    if args.board_width_mm <= 0 or args.board_height_mm <= 0:
        raise SystemExit("error: board dimensions must be positive")
    if args.printer_margin_mm < 0 or args.printer_margin_mm >= 60:
        raise SystemExit("error: printer margin must be in [0, 60) mm")
    if args.overlap_mm < 0:
        raise SystemExit("error: overlap must be non-negative")

    usable_w_mm = A4_WIDTH_MM - 2.0 * args.printer_margin_mm
    usable_h_mm = A4_HEIGHT_MM - 2.0 * args.printer_margin_mm
    step_w_mm = usable_w_mm - args.overlap_mm
    step_h_mm = usable_h_mm - args.overlap_mm
    if usable_w_mm <= 0 or usable_h_mm <= 0 or step_w_mm <= 0 or step_h_mm <= 0:
        raise SystemExit("error: margin/overlap leaves no printable tile area")

    image = cv2.imread(args.input_png, cv2.IMREAD_GRAYSCALE)
    if image is None:
        raise SystemExit(f"error: cannot read {args.input_png}")
    image_h_px, image_w_px = image.shape[:2]
    px_per_mm_x = image_w_px / args.board_width_mm
    px_per_mm_y = image_h_px / args.board_height_mm

    page_cols = max(1, math.ceil((args.board_width_mm - args.overlap_mm) / step_w_mm))
    page_rows = max(1, math.ceil((args.board_height_mm - args.overlap_mm) / step_h_mm))
    out_dir = Path(args.output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    for row in range(page_rows):
        for col in range(page_cols):
            crop_x_mm = col * step_w_mm
            crop_y_mm = row * step_h_mm
            crop_w_mm = min(usable_w_mm, args.board_width_mm - crop_x_mm)
            crop_h_mm = min(usable_h_mm, args.board_height_mm - crop_y_mm)

            x0 = int(round(crop_x_mm * px_per_mm_x))
            y0 = int(round(crop_y_mm * px_per_mm_y))
            x1 = int(round((crop_x_mm + crop_w_mm) * px_per_mm_x))
            y1 = int(round((crop_y_mm + crop_h_mm) * px_per_mm_y))
            crop = image[y0:y1, x0:x1]
            if crop.size == 0:
                continue

            output = out_dir / f"tile_r{row + 1:02d}_c{col + 1:02d}.svg"
            _render_svg(
                output,
                crop,
                col,
                row,
                page_cols,
                page_rows,
                crop_x_mm,
                crop_y_mm,
                crop_w_mm,
                crop_h_mm,
                args.printer_margin_mm,
                args.printer_margin_mm,
            )

    print(f"wrote {page_rows * page_cols} A4 SVG tiles to {out_dir}")
    print("print each SVG at 100% / actual size / no scaling")
    print("red dashed boxes and corner marks show tile crop bounds; adjacent pages overlap.")


if __name__ == "__main__":
    main()
